### ISSUE TITLE
IllegalStateException during Pause of Video

### ISSUE THREAD

**Issue by kingargyle** [NineWorlds/serenity-android#275]
Thread: main, Exception: java.lang.IllegalStateException at android.media.MediaPlayer.isPlaying(Native Method) at us.nineworlds.serenity.ui.video.player.SerenityMediaPlayerControl.isPlaying(SerenityMediaPlayerControl.java:36) at us.nineworlds.serenity.ui.video.player.PauseOnClickListener.doPauseResume(PauseOnClickListener.java:23) at us.nineworlds.serenity.ui.video.player.PauseOnClickListener.onClick(PauseOnClickListener.java:16) at android.view.View.performClick(View.java:4421) at android.view.View$PerformClick.run(View.java:18190) at android.os.Handler.handleCallback(Handler.java:725) at android.os.Handler.dispatchMessage(Handler.java:92) at android.os.Looper.loop(Looper.java:175) at android.app.ActivityThread.main(ActivityThread.java:5279) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:511) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) at dalvik.system.NativeStart.main(Native Method)

**Comment by kingargyle** [comment]
New player so will need to check this again if it happens with Exoplayer.
