### ISSUE TITLE
Download Handler throwing IllegalArgumentException

### ISSUE THREAD

**Issue by kingargyle** [NineWorlds/serenity-android#276]
Thread: main, Exception: java.lang.RuntimeException: Unable to destroy activity {us.nineworlds.serenity/us.nineworlds.serenity.MainActivity}: java.lang.IllegalArgumentException: Service not registered: us.nineworlds.serenity.handlers.DownloadHandler$DownloadServiceConnection@41be2ab0 at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3484) at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3502) at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3702) at android.app.ActivityThread.access$700(ActivityThread.java:146) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1249) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:137) at android.app.ActivityThread.main(ActivityThread.java:5104) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:511) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) at dalvik.system.NativeStart.main(Native Method) Caused by: java.lang.IllegalArgumentException: Service not registered: us.nineworlds.serenity.handlers.DownloadHandler$DownloadServiceConnection@41be2ab0 at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:931) at android.app.ContextImpl.unbindService(ContextImpl.java:1758) at android.content.ContextWrapper.unbindService(ContextWrapper.java:511) at us.nineworlds.serenity.MainActivity.onDestroyMainActivity(MainActivity.java:220) at us.nineworlds.serenity.MainActivity.onDestroy(MainActivity.java) at android.app.Activity.performDestroy(Activity.java:5362) at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1118) at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3471) ... 12 more

**Comment by kingargyle** [comment]
Won't fix.  downloads are out of scope for 2.0.0.
