### ISSUE TITLE
NPE during Music Retrieval.

### ISSUE THREAD

**Issue by kingargyle** [NineWorlds/serenity-android#277]
Thread: IntentService[MusicRetrievalIntentService], Exception: java.lang.NullPointerException at us.nineworlds.serenity.core.services.MusicRetrievalIntentService.onHandleIntent(MusicRetrievalIntentService.java:81) at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:137) at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by kingargyle** [comment]
Closing as removing support for Music Player.
