### ISSUE TITLE
NPE in Category Retrieval Service

### ISSUE THREAD

**Issue by kingargyle** [NineWorlds/serenity-android#289]
java.lang.NullPointerException
at us.nineworlds.serenity.core.services.CategoryRetrievalIntentService.onHandleIntent(CategoryRetrievalIntentService.java:59)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by kingargyle** [comment]
Closing as the Music support has currently been removed.
