### ISSUE TITLE
Crash when selecting Plex Server

### ISSUE THREAD

**Issue by kingargyle** [NineWorlds/serenity-android#377]
Main Menu is displayed and then a crash occurs.

Steps to reproduce:
1. Launch the App.
2. Select a Plexserver to access.
3. App crashes after displaying the main menu.

**Comment by kingargyle** [comment]
One of the stack traces:

Thread: AsyncTask #1, Exception: java.lang.RuntimeException: An error occurred while executing doInBackground() at android.os.AsyncTask$3.done(AsyncTask.java:353) at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383) at java.util.concurrent.FutureTask.setException(FutureTask.java:252) at java.util.concurrent.FutureTask.run(FutureTask.java:271) at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) at java.lang.Thread.run(Thread.java:764) Caused by: java.lang.NumberFormatException: For input string: "/library/metadata/181" at java.lang.Integer.parseInt(Integer.java:597) at java.lang.Integer.parseInt(Integer.java:643) at us.nineworlds.serenity.core.services.RecommendAsyncTask.buildMovieRecommendation(RecommendAsyncTask.java:75) at us.nineworlds.serenity.core.services.RecommendAsyncTask.doInBackground(RecommendAsyncTask.java:45) at android.os.AsyncTask$2.call(AsyncTask.java:333) at java.util.concurrent.FutureTask.run(FutureTask.java:266) ... 4 more

**Comment by kingargyle** [comment]
Still need to fix this, but turning Recommendations off allows the browsing in Plex to work again.

**Comment by kingargyle** [comment]
"Fixed" for now, the recommendations will only run on Android TV 7.0 devices and the crash will be caught in case it does happen.
