### ISSUE TITLE
Implement Movie Search for Emby

### ISSUE THREAD

**Issue by kingargyle** [NineWorlds/serenity-android#380]
Plex client currently only implementes Movie Search, so need to implement same functionality for Emby.

    Process: us.nineworlds.serenity, PID: 7092
    kotlin.NotImplementedError: An operation is not implemented: not implemented
        at us.nineworlds.serenity.emby.server.api.EmbyAPIClient.searchMovies(EmbyAPIClient.kt:233)
        at us.nineworlds.serenity.core.services.MovieSearchIntentService.retrieveVideos(MovieSearchIntentService.java:52)
        at us.nineworlds.serenity.core.services.MoviesRetrievalIntentService.createPosters(MoviesRetrievalIntentService.java:88)
        at us.nineworlds.serenity.core.services.MovieSearchIntentService.onHandleIntent(MovieSearchIntentService.java:47)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by kingargyle** [comment]
Basic search for Movies is implemented.
