### ISSUE TITLE
Crash on MovieBrowserActivity during Create

### ISSUE THREAD

**Issue by kingargyle** [NineWorlds/serenity-android#397]
Thread: main, Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{us.nineworlds.serenity/us.nineworlds.serenity.ui.browser.movie.MovieBrowserActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0c0086 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2330) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) at android.app.ActivityThread.access$800(ActivityThread.java:156) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:135) at android.app.ActivityThread.main(ActivityThread.java:5278) at java.lang.reflect.Method.invoke(Native Method) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0c0086 at android.content.res.Resources.getValue(Resources.java:1266) at android.content.res.Resources.loadXmlResourceParser(Resources.java:2649) at android.content.res.Resources.getLayout(Resources.java:1082) at android.view.LayoutInflater.inflate(LayoutInflater.java:412) at android.support.v7.app.WindowDecorActionBar.setCustomView(WindowDecorActionBar.java:363) at us.nineworlds.serenity.ui.browser.movie.MovieBrowserActivity.onCreate(MovieBrowserActivity.java:73) at android.app.Activity.performCreate(Activity.java:6033) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2283) ... 10 more

**Comment by kingargyle** [comment]
Note this issue is because somebody was trying to run the app on a Samsung phone.  Phones are not supported.
