### ISSUE TITLE
Glide cannot load on a Destroyed Activity

### ISSUE THREAD

**Issue by kingargyle** [NineWorlds/serenity-android#399]
Thread: main, Exception: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134) at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:125) at com.bumptech.glide.Glide.with(Glide.java:669) at us.nineworlds.serenity.ui.browser.tv.TVShowGridOnItemSelectedListener.changeBackgroundImage(TVShowGridOnItemSelectedListener.java:111) at us.nineworlds.serenity.ui.browser.tv.TVShowGridOnItemSelectedListener.access$000(TVShowGridOnItemSelectedListener.java:52) at us.nineworlds.serenity.ui.browser.tv.TVShowGridOnItemSelectedListener$1.run(TVShowGridOnItemSelectedListener.java:84) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:135) at android.app.ActivityThread.main(ActivityThread.java:5597) at java.lang.reflect.Method.invoke(Native Method) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) |  
-- | --

**Comment by kingargyle** [comment]
Make sure that we aren't using the Activity context, but the viewholder's view context.

https://github.com/bumptech/glide/issues/1484#issuecomment-272106225

**Comment by kingargyle** [comment]
Fixed.  Checked to make sure the context wasn't destroyed before adding it to glide.
