### ISSUE TITLE
NPE when looking up Supported Codecs on Device

### ISSUE THREAD

**Issue by kingargyle** [NineWorlds/serenity-android#417]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at us.nineworlds.serenity.ui.video.player.ExoplayerPresenter.isDirectPlaySupportedForContainer$serenity_app_release(ExoplayerPresenter.kt:167)
       at us.nineworlds.serenity.ui.video.player.ExoplayerPresenter.transcoderUrl(ExoplayerPresenter.kt:175)
       at us.nineworlds.serenity.ui.video.player.ExoplayerPresenter.playBackFromVideoQueue(ExoplayerPresenter.kt:156)
       at us.nineworlds.serenity.ui.video.player.ExoplayerVideoActivity.onStart(ExoplayerVideoActivity.kt:96)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333)
       at android.app.Activity.performStart(Activity.java:6992)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by kingargyle** [comment]
Fixed this issue by replacing the call that was being used, and rewrote determination if direct play or transcoding should be used.   This should be more reliable going forward.
