### ISSUE TITLE
Audio Sink Error on TCL Android TV Beyond TV

### ISSUE THREAD

**Issue by kingargyle** [NineWorlds/serenity-android#458]
2022-04-06 21:11:34.391 1246-2130/us.nineworlds.serenity E/IAudioFlinger: createTrack returned error -38
2022-04-06 21:11:34.391 1246-2130/us.nineworlds.serenity E/AudioTrack: AudioFlinger could not create track, status: -38 output -1870510120
2022-04-06 21:11:34.392 1246-2130/us.nineworlds.serenity E/AudioTrack-JNI: Error -38 initializing AudioTrack
2022-04-06 21:11:34.392 1246-2130/us.nineworlds.serenity D/AudioTrack: no metrics gathered, track status=-38
2022-04-06 21:11:34.395 1246-2130/us.nineworlds.serenity E/android.media.AudioTrack: Error code -20 when initializing AudioTrack.
2022-04-06 21:11:34.405 1246-2130/us.nineworlds.serenity E/MediaCodecAudioRenderer: Audio sink error
      com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 252, 258720)
        at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2052)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:854)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:660)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:736)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:639)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1839)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:778)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2022-04-06 21:11:34.440 1246-2130/us.nineworlds.serenity E/IAudioFlinger: createTrack returned error -38
2022-04-06 21:11:34.440 1246-2130/us.nineworlds.serenity E/AudioTrack: AudioFlinger could not create track, status: -38 output -1870510120
2022-04-06 21:11:34.440 1246-2130/us.nineworlds.serenity E/AudioTrack-JNI: Error -38 initializing AudioTrack
2022-04-06 21:11:34.440 1246-2130/us.nineworlds.serenity D/AudioTrack: no metrics gathered, track status=-38
2022-04-06 21:11:34.440 1246-2130/us.nineworlds.serenity E/android.media.AudioTrack: Error code -20 when initializing AudioTrack.
2022-04-06 21:11:34.448 1246-2130/us.nineworlds.serenity E/MediaCodecAudioRenderer: Audio sink error
      com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 252, 258720)
        at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2052)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:854)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:660)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:736)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:639)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1839)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:778)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2022-04-06 21:11:34.492 1246-2130/us.nineworlds.serenity E/IAudioFlinger: createTrack returned error -38
2022-04-06 21:11:34.492 1246-2130/us.nineworlds.serenity E/AudioTrack: AudioFlinger could not create track, status: -38 output -1870510120
2022-04-06 21:11:34.494 1246-2130/us.nineworlds.serenity E/AudioTrack-JNI: Error -38 initializing AudioTrack
2022-04-06 21:11:34.494 1246-2130/us.nineworlds.serenity D/AudioTrack: no metrics gathered, track status=-38
2022-04-06 21:11:34.494 1246-2130/us.nineworlds.serenity E/android.media.AudioTrack: Error code -20 when initializing AudioTrack.
2022-04-06 21:11:34.500 1246-2130/us.nineworlds.serenity E/MediaCodecAudioRenderer: Audio sink error
      com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 252, 258720)
        at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2052)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:854)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:660)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:736)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:639)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1839)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:778)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2022-04-06 21:11:34.515 1246-2130/us.nineworlds.serenity E/IAudioFlinger: createTrack returned error -38
2022-04-06 21:11:34.515 1246-2130/us.nineworlds.serenity E/AudioTrack: AudioFlinger could not create track, status: -38 output -1870510120
2022-04-06 21:11:34.526 1246-2130/us.nineworlds.serenity E/AudioTrack-JNI: Error -38 initializing AudioTrack
2022-04-06 21:11:34.526 1246-2130/us.nineworlds.serenity D/AudioTrack: no metrics gathered, track status=-38
2022-04-06 21:11:34.526 1246-2130/us.nineworlds.serenity E/android.media.AudioTrack: Error code -20 when initializing AudioTrack.
2022-04-06 21:11:34.529 1246-2130/us.nineworlds.serenity E/MediaCodecAudioRenderer: Audio sink error
      com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 252, 258720)
        at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2052)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:854)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:660)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:736)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:639)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1839)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:778)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2022-04-06 21:11:34.545 1246-2130/us.nineworlds.serenity E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [6, 48000]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 252, 258720)
        at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2052)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:854)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:660)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:736)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:639)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1839)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:778)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
          Suppressed: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 252, 258720)
              ... 12 more

**Comment by kingargyle** [comment]
This issue occurred while in tunneling mode on the TCL Beyond TV 5.   For this particular device we disable tunneling support and fall back to the default media support.
